default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: syndicator_development

test:
  <<: *default
  database: syndicator_test

production:
  <<: *default
  database: syndicator_production